import numpy as np
l = [2, 5, 7, 9, 12.7, 45, 67, 1, 2]
a = np.array(l)
print("a          - {}".format(a))
print("type(a)    - {}".format(type(a)))
print("a.ndim     - {}".format(a.ndim))
print("a.shape    - {}".format(a.shape))
print("a.size     - {}".format(a.size))
print("a.dtype    - {}".format(a.dtype))
print("a.itemsize - {}".format(a.itemsize))

print("========================")
a = np.array([2, 5, 7, 9, 12, "pawan"])
print("a          - {}".format(a))
print("type(a)    - {}".format(type(a)))
print("a.ndim     - {}".format(a.ndim))
print("a.shape    - {}".format(a.shape))
print("a.size     - {}".format(a.size))
print("a.dtype    - {}".format(a.dtype))
print("a.itemsize - {}".format(a.itemsize))
print("========================")
a = np.array([[2, 3, 4, 6], [56, 78, 89, 4], [2, 3, 56, 12]])
print("a          - {}".format(a))
print("type(a)    - {}".format(type(a)))
print("a.ndim     - {}".format(a.ndim))
print("a.shape    - {}".format(a.shape))
print("a.size     - {}".format(a.size))
print("a.dtype    - {}".format(a.dtype))
print("a.itemsize - {}".format(a.itemsize))
print("a.reshape  - {}".format(a.reshape(12, )))
b = a.reshape(12, )
print("Now shape is - {}".format(b.shape))
print("========================")
a = np.array([[[2, 3, 4, 6], [56, 78, 89, 4], [2, 3, 56, 12]]], dtype=np.int64)
print("a          - {}".format(a))
print("type(a)    - {}".format(type(a)))
print("a.ndim     - {}".format(a.ndim))
print("a.shape    - {}".format(a.shape))
print("a.size     - {}".format(a.size))
print("a.dtype    - {}".format(a.dtype))
print("a.itemsize - {}".format(a.itemsize))
print("========================")

a = np.array([[[[2, 3, 4, 6], [56, 78, 89, 4], [2, 3, 56, 12]]]], dtype=np.complex)
print("a          - {}".format(a))
print("type(a)    - {}".format(type(a)))
print("a.ndim     - {}".format(a.ndim))
print("a.shape    - {}".format(a.shape))
print("a.size     - {}".format(a.size))
print("a.dtype    - {}".format(a.dtype))
print("a.itemsize - {}".format(a.itemsize))
